# Generated by Django 4.0.4 on 2022-12-25 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Todo_user',
        ),
    ]
