# Generated by Django 4.0.4 on 2022-12-25 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0002_delete_todo_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Todo_user',
            fields=[
                ('username', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'logged_user',
            },
        ),
    ]
