# Generated by Django 4.0.4 on 2022-12-28 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0003_todo_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Todo_app_userTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('detail', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'usertask',
            },
        ),
        migrations.CreateModel(
            name='userdata',
            fields=[
                ('username', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('table_id', models.IntegerField()),
            ],
            options={
                'db_table': 'userdata',
            },
        ),
        migrations.DeleteModel(
            name='Todo_user',
        ),
    ]
