# Generated by Django 4.0.4 on 2019-11-29 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0005_delete_userdata_todo_app_usertask_is_complete'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo_app_usertask',
            name='username',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
