# Generated by Django 4.0.4 on 2022-12-28 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0006_todo_app_usertask_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo_app_usertask',
            name='title_id',
            field=models.IntegerField(default=0, unique=True),
        ),
        migrations.AlterField(
            model_name='todo_app_usertask',
            name='username',
            field=models.CharField(default='', max_length=20),
        ),
    ]
