# Generated by Django 4.0.4 on 2022-12-28 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0007_todo_app_usertask_title_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo_app_usertask',
            name='id',
        ),
        migrations.AlterField(
            model_name='todo_app_usertask',
            name='username',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
