# Generated by Django 4.0.4 on 2022-12-28 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0008_remove_todo_app_usertask_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo_app_usertask',
            name='title_id',
        ),
        migrations.AddField(
            model_name='todo_app_usertask',
            name='id',
            field=models.IntegerField(default=0),
        ),
    ]
