# Generated by Django 4.0.4 on 2023-01-04 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0013_alter_todo_app_usertask_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo_app_usertask',
            name='title_id',
            field=models.IntegerField(),
        ),
        migrations.AlterModelTable(
            name='todo_app_usertask',
            table=None,
        ),
    ]
